### ISSUE TITLE
Some code is missing

### ISSUE THREAD

**Issue by EmbeddedVito** [STMicroelectronics/STM32CubeF3#19]
Hi,

I am trying to use the CMSIS-DSP library with my Nucleo Board (F3) and I need to test the Levinson Durbin algorithm. I have seen that this function is described and defined here https://www.keil.com/pack/doc/cmsis/DSP/html/group__LD.html, but i cannot use that in my code because there is not inside the CMSIS Library. I have even look for it inside the G4 Library, but is missing even there.
Am I missing something? Do I need to Install or download anything else?

Thank you,

EmbeddedVito.
<img width="794" alt="Schermata 2022-04-15 alle 12 43 58" src="https://user-images.githubusercontent.com/103099923/163561973-3bf27655-fd77-4aa0-88ce-fa7195e30c59.png">

**Comment by ASELSTM** [comment]
Hi @EmbeddedVito,

Unfortunately, we don't address aspects related to **CMSIS-DSP** library in our GitHub repositories as the library come from Arm and we use it as is. Therefore, these files are out of the scope of STMicroelectronics. You may report this issue to the [ARM](https://github.com/ARM-software) GitHub.

Please allow me to close this issue now. Thank you again for your comprehension and for your contribution.

With regards,
