### ISSUE TITLE
STM32373C-EVAL hx8347i.h

### ISSUE THREAD

**Issue by lba934** [STMicroelectronics/STM32CubeF3#5]
Hello 

I need help with this...
![image](https://user-images.githubusercontent.com/69297793/89505869-90bea400-d7ca-11ea-90b0-3b865f9a9648.png)
![image](https://user-images.githubusercontent.com/69297793/89505981-af249f80-d7ca-11ea-995a-ad16c8222088.png)
![image](https://user-images.githubusercontent.com/69297793/89506152-fc087600-d7ca-11ea-8ea7-06795ed63030.png)

As you can see I added the libraries (hx8347i.h and stm32373c_eval_lcd.h) to my project. However, it cannot be found. How can I fix this?

Thank you!

**Comment by ASELSTM** [comment]
Hi @lba934,

Please make sure that you have included the right path to the BSP/Components in your project.

For that open your project **properties** then click on the **C/C++ Build** tab and select **Settings** then **Include paths**.
If not present please add the following path `../../../../../../../Drivers/BSP/Components/Common` and adjust it with your tree structure.

With regards,
